---
apiVersion: v1
kind: Service
metadata:
  name: flex-gateway-service
  namespace: gateway-internal
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 8080
  selector:
    app: flex-gateway